name: Rust Tests

on:
  pull_request:
    branches: [ '*' ]
  workflow_run:
    workflows: ["Rust Clippy Lint"]
    types:
      - completed
    branches: [ '*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')

    steps:
    - uses: actions/checkout@v3
    - name: Run Tests
      run: cargo test --verbose --all-targets
